In [1]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path.cwd()
DATA_DIR = PROJECT_DIR / "project_data"

In [2]:
possesion_data = pd.read_csv(DATA_DIR / 'player_possession.csv')

# Select only midfielders from the 22/23 season
mf_possesion_data = possesion_data[(possesion_data['Season_End_Year'] == 2023) & (possesion_data['Pos'].str.contains('MF', na=False))].drop(columns='Url')

# Check for missing data
# mf_possesion_data.isna().sum()

# Remove columns that contains only NaN values
mf_possesion_data_no_nan_col = mf_possesion_data[[col for col in mf_possesion_data.columns if mf_possesion_data[col].isna().sum() != 1202]]
mf_possesion_data_no_nan_col

# Check
# mf_possesion_data_no_nan_col.isna().sum()

# Drop columns that is calculated from other columns (e.g., percentages)
mf_possesion_data_no_redundant = mf_possesion_data_no_nan_col[[col for col in mf_possesion_data_no_nan_col.columns if '_percent_' not in col]]
mf_possesion_data_no_redundant

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,Touches_Touches,...,Mid 3rd_Touches,Att 3rd_Touches,Att Pen_Touches,Live_Touches,Succ_Dribbles,Att_Dribbles,Rec_Receiving,Prog_Receiving,Mis_Dribbles,Dis_Dribbles
13824,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,31-280,1991.0,1.6,78.0,...,42.0,31.0,1.0,78.0,5.0,8.0,50.0,9.0,3.0,4.0
13825,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,26-154,1996.0,7.3,317.0,...,143.0,133.0,16.0,317.0,8.0,20.0,188.0,27.0,25.0,13.0
13826,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,MF,30-225,1992.0,1.1,67.0,...,27.0,33.0,3.0,67.0,5.0,11.0,44.0,3.0,4.0,0.0
13828,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,MF,20-276,2002.0,3.1,144.0,...,63.0,59.0,2.0,144.0,2.0,6.0,87.0,12.0,4.0,5.0
13829,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,MF,36-219,1986.0,6.2,444.0,...,308.0,78.0,3.0,444.0,3.0,6.0,305.0,6.0,7.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,2023,Wolves,Premier League,Matheus Nunes,POR,MF,24-059,1998.0,9.0,415.0,...,170.0,171.0,25.0,415.0,10.0,24.0,293.0,49.0,15.0,12.0
16134,2023,Wolves,Premier League,Daniel Podence,POR,"MF,FW",27-004,1995.0,9.6,425.0,...,162.0,224.0,35.0,425.0,5.0,21.0,317.0,56.0,23.0,18.0
16136,2023,Wolves,Premier League,Nélson Semedo,POR,"DF,MF",28-343,1993.0,5.3,312.0,...,133.0,101.0,6.0,312.0,4.0,13.0,184.0,18.0,12.0,6.0
16137,2023,Wolves,Premier League,Adama Traoré,ESP,MF,26-273,1996.0,4.7,222.0,...,78.0,119.0,11.0,222.0,11.0,26.0,171.0,34.0,20.0,8.0
16138,2023,Wolves,Premier League,Boubacar Traoré,MLI,MF,21-066,2001.0,1.3,66.0,...,38.0,5.0,0.0,66.0,0.0,1.0,32.0,2.0,0.0,1.0

In [3]:
mf_possesion_data_no_redundant.isna().sum()

Season_End_Year    0
Squad              0
Comp               0
Player             0
Nation             0
Pos                0
Age                0
Born               0
Mins_Per_90        0
Touches_Touches    2
Def Pen_Touches    2
Def 3rd_Touches    2
Mid 3rd_Touches    2
Att 3rd_Touches    2
Att Pen_Touches    2
Live_Touches       2
Succ_Dribbles      2
Att_Dribbles       2
Rec_Receiving      2
Prog_Receiving     2
Mis_Dribbles       2
Dis_Dribbles       2
dtype: int64

In [4]:
passing_data = pd.read_csv(DATA_DIR / 'player_passing.csv')

mf_passing_data = passing_data[(passing_data['Season_End_Year'] == 2023) & (passing_data['Pos'].str.contains('MF', na=False))].drop(columns='Url')

# Check for missing data
# mf_passing_data.isna().sum()

# Remove columns that contains only NaN values
mf_passing_data_no_nan_col = mf_passing_data[[col for col in mf_passing_data.columns if mf_passing_data[col].isna().sum() != 1202]]
mf_passing_data_no_nan_col

# Check
# mf_passing_data_no_nan_col.isna().sum()

# Drop columns that is calculated from other columns (e.g., percentages)
mf_passing_data_no_redundant = mf_passing_data_no_nan_col[[col for col in mf_passing_data_no_nan_col.columns if '_percent_' not in col]]
mf_passing_data_no_redundant

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,Cmp_Total,...,Att_Long,Ast,xA,KP,Final_Third,PPA,CrsPA,Prog,xAG,A_minus_xAG
13824,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,31-280,1991.0,1.6,46.0,...,8.0,0,0.2,5.0,7.0,4.0,1.0,8.0,0.2,-0.2
13825,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,26-154,1996.0,7.3,130.0,...,24.0,0,0.2,3.0,17.0,4.0,1.0,23.0,0.1,-0.1
13826,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,MF,30-225,1992.0,1.1,37.0,...,8.0,0,0.2,3.0,5.0,1.0,0.0,7.0,0.1,-0.1
13828,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,MF,20-276,2002.0,3.1,75.0,...,14.0,0,0.1,3.0,1.0,2.0,2.0,1.0,0.1,-0.1
13829,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,MF,36-219,1986.0,6.2,336.0,...,58.0,0,0.6,6.0,44.0,4.0,1.0,28.0,0.5,-0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,2023,Wolves,Premier League,Matheus Nunes,POR,MF,24-059,1998.0,9.0,243.0,...,50.0,1,0.5,11.0,21.0,8.0,1.0,20.0,0.8,0.2
16134,2023,Wolves,Premier League,Daniel Podence,POR,"MF,FW",27-004,1995.0,9.6,214.0,...,39.0,0,1.1,19.0,18.0,19.0,4.0,44.0,1.4,-1.4
16136,2023,Wolves,Premier League,Nélson Semedo,POR,"DF,MF",28-343,1993.0,5.3,202.0,...,26.0,0,0.2,4.0,16.0,5.0,2.0,11.0,0.1,-0.1
16137,2023,Wolves,Premier League,Adama Traoré,ESP,MF,26-273,1996.0,4.7,103.0,...,19.0,0,0.7,8.0,5.0,9.0,7.0,11.0,0.7,-0.7
16138,2023,Wolves,Premier League,Boubacar Traoré,MLI,MF,21-066,2001.0,1.3,41.0,...,4.0,0,0.0,0.0,4.0,0.0,0.0,3.0,0.0,0.0

In [5]:
mf_passing_data_no_redundant.isna().sum()

Season_End_Year    0
Squad              0
Comp               0
Player             0
Nation             0
Pos                0
Age                0
Born               0
Mins_Per_90        0
Cmp_Total          2
Att_Total          2
TotDist_Total      2
PrgDist_Total      2
Cmp_Short          2
Att_Short          2
Cmp_Medium         2
Att_Medium         2
Cmp_Long           2
Att_Long           2
Ast                0
xA                 2
KP                 2
Final_Third        2
PPA                2
CrsPA              2
Prog               2
xAG                2
A_minus_xAG        2
dtype: int64

In [6]:
shooting_data = pd.read_csv(DATA_DIR / 'player_shooting.csv', low_memory=False)

mf_shooting_data = shooting_data[(shooting_data['Season_End_Year'] == 2023) & (shooting_data['Pos'].str.contains('MF', na=False))].drop(columns='Url')

# Drop columns that is calculated from other columns (e.g., percentages)
mf_shooting_data_no_redundant = mf_shooting_data[[col for col in mf_shooting_data.columns if '_percent_' not in col]]

# Check that there are still columns with many missing data
# mf_shooting_data_no_redundant.isna().sum()

# Drop those columns
mf_shooting_data_no_redundant = mf_shooting_data_no_redundant.drop(columns=['G_per_Sh_Standard', 'G_per_SoT_Standard', 'Dist_Standard', 'npxG_per_Sh_Expected'])
mf_shooting_data_no_redundant

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,Gls_Standard,...,SoT_Standard,Sh_per_90_Standard,SoT_per_90_Standard,PK_Standard,PKatt_Standard,FK_Standard,xG_Expected,npxG_Expected,G_minus_xG_Expected,np:G_minus_xG_Expected
35669,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,31-280,1991.0,1.6,0,...,0.0,1.25,0.00,0.0,0.0,1.0,0.1,0.1,-0.1,-0.1
35670,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,26-154,1996.0,7.3,1,...,4.0,1.37,0.55,0.0,0.0,0.0,0.9,0.9,0.1,0.1
35671,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,MF,30-225,1992.0,1.1,0,...,1.0,1.84,0.92,0.0,0.0,1.0,0.0,0.0,0.0,0.0
35673,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,MF,20-276,2002.0,3.1,0,...,2.0,1.94,0.65,0.0,0.0,0.0,0.2,0.2,-0.2,-0.2
35674,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,MF,36-219,1986.0,6.2,0,...,0.0,0.32,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37978,2023,Wolves,Premier League,Matheus Nunes,POR,MF,24-059,1998.0,9.0,0,...,3.0,1.56,0.33,0.0,0.0,0.0,1.1,1.1,-1.1,-1.1
37979,2023,Wolves,Premier League,Daniel Podence,POR,"MF,FW",27-004,1995.0,9.6,2,...,7.0,2.09,0.73,0.0,0.0,0.0,1.6,1.6,0.4,0.4
37981,2023,Wolves,Premier League,Nélson Semedo,POR,"DF,MF",28-343,1993.0,5.3,0,...,0.0,0.19,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37982,2023,Wolves,Premier League,Adama Traoré,ESP,MF,26-273,1996.0,4.7,1,...,1.0,1.26,0.21,0.0,0.0,0.0,0.5,0.5,0.5,0.5
37983,2023,Wolves,Premier League,Boubacar Traoré,MLI,MF,21-066,2001.0,1.3,0,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
mf_shooting_data_no_redundant.isna().sum()

Season_End_Year           0
Squad                     0
Comp                      0
Player                    0
Nation                    0
Pos                       0
Age                       0
Born                      0
Mins_Per_90               0
Gls_Standard              0
Sh_Standard               0
SoT_Standard              0
Sh_per_90_Standard        0
SoT_per_90_Standard       0
PK_Standard               0
PKatt_Standard            0
FK_Standard               2
xG_Expected               2
npxG_Expected             2
G_minus_xG_Expected       2
np:G_minus_xG_Expected    2
dtype: int64

In [8]:
defense_data = pd.read_csv(DATA_DIR / 'player_defense.csv')

mf_defense_data = defense_data[(defense_data['Season_End_Year'] == 2023) & (defense_data['Pos'].str.contains('MF', na=False))].drop(columns='Url')

# Check for missing data
# mf_defense_data.isna().sum()

# Remove columns that contains only NaN values
mf_defense_data_no_nan_col = mf_defense_data[[col for col in mf_defense_data.columns if mf_defense_data[col].isna().sum() != 1202]]
mf_defense_data_no_nan_col

# Drop columns that is calculated from other columns (e.g., percentages)
mf_defense_data_no_redundant = mf_defense_data_no_nan_col[[col for col in mf_defense_data_no_nan_col.columns if '_percent_' not in col]]
mf_defense_data_no_redundant

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,Tkl_Tackles,...,Tkl_Vs,Att_Vs,Past_Vs,Blocks_Blocks,Sh_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err
13824,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,31-280,1991.0,1.6,6.0,...,2.0,4.0,2.0,1.0,0.0,1.0,1.0,7.0,0.0,0.0
13825,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,26-154,1996.0,7.3,22.0,...,10.0,15.0,5.0,8.0,2.0,6.0,9.0,31.0,2.0,0.0
13826,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,MF,30-225,1992.0,1.1,6.0,...,3.0,4.0,1.0,1.0,0.0,1.0,0.0,6.0,0.0,0.0
13828,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,MF,20-276,2002.0,3.1,11.0,...,4.0,5.0,1.0,5.0,1.0,4.0,2.0,13.0,2.0,0.0
13829,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,MF,36-219,1986.0,6.2,10.0,...,5.0,8.0,3.0,5.0,0.0,5.0,8.0,18.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,2023,Wolves,Premier League,Matheus Nunes,POR,MF,24-059,1998.0,9.0,20.0,...,5.0,12.0,7.0,10.0,0.0,10.0,2.0,22.0,12.0,0.0
16134,2023,Wolves,Premier League,Daniel Podence,POR,"MF,FW",27-004,1995.0,9.6,9.0,...,2.0,8.0,6.0,8.0,0.0,8.0,2.0,11.0,2.0,0.0
16136,2023,Wolves,Premier League,Nélson Semedo,POR,"DF,MF",28-343,1993.0,5.3,20.0,...,11.0,13.0,2.0,10.0,4.0,6.0,5.0,25.0,11.0,0.0
16137,2023,Wolves,Premier League,Adama Traoré,ESP,MF,26-273,1996.0,4.7,3.0,...,1.0,2.0,1.0,4.0,0.0,4.0,0.0,3.0,3.0,0.0
16138,2023,Wolves,Premier League,Boubacar Traoré,MLI,MF,21-066,2001.0,1.3,5.0,...,0.0,2.0,2.0,2.0,2.0,0.0,3.0,8.0,0.0,0.0

In [9]:
mf_defense_data_no_redundant.isna().sum()

Season_End_Year    0
Squad              0
Comp               0
Player             0
Nation             0
Pos                0
Age                0
Born               0
Mins_Per_90        0
Tkl_Tackles        2
TklW_Tackles       0
Def 3rd_Tackles    2
Mid 3rd_Tackles    2
Att 3rd_Tackles    2
Tkl_Vs             2
Att_Vs             2
Past_Vs            2
Blocks_Blocks      2
Sh_Blocks          2
Pass_Blocks        2
Int                0
Tkl+Int            2
Clr                2
Err                2
dtype: int64

In [10]:
gca_data = pd.read_csv(DATA_DIR / 'player_gca.csv')

mf_gca_data = gca_data[(gca_data['Season_End_Year'] == 2023) & (gca_data['Pos'].str.contains('MF', na=False))].drop(columns='Url')
mf_gca_data

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,SCA_SCA,...,Fld_SCA,Def_SCA,GCA_GCA,GCA90_GCA,PassLive_GCA,PassDead_GCA,Drib_GCA,Sh_GCA,Fld_GCA,Def_GCA
13824,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,MF,31-280,1991.0,1.6,6.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
13825,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,MF,26-154,1996.0,7.3,15.0,...,1.0,2.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
13826,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,MF,30-225,1992.0,1.1,6.0,...,1.0,0.0,2.0,1.84,0.0,0.0,2.0,0.0,0.0,0.0
13828,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,MF,20-276,2002.0,3.1,9.0,...,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
13829,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,MF,36-219,1986.0,6.2,11.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16133,2023,Wolves,Premier League,Matheus Nunes,POR,MF,24-059,1998.0,9.0,24.0,...,1.0,1.0,1.0,0.11,1.0,0.0,0.0,0.0,0.0,0.0
16134,2023,Wolves,Premier League,Daniel Podence,POR,"MF,FW",27-004,1995.0,9.6,33.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
16136,2023,Wolves,Premier League,Nélson Semedo,POR,"DF,MF",28-343,1993.0,5.3,7.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
16137,2023,Wolves,Premier League,Adama Traoré,ESP,MF,26-273,1996.0,4.7,14.0,...,1.0,0.0,1.0,0.21,0.0,0.0,0.0,1.0,0.0,0.0
16138,2023,Wolves,Premier League,Boubacar Traoré,MLI,MF,21-066,2001.0,1.3,1.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
mf_gca_data.isna().sum()

Season_End_Year    0
Squad              0
Comp               0
Player             0
Nation             0
Pos                0
Age                0
Born               0
Mins_Per_90        0
SCA_SCA            2
SCA90_SCA          2
PassLive_SCA       2
PassDead_SCA       2
Drib_SCA           2
Sh_SCA             2
Fld_SCA            2
Def_SCA            2
GCA_GCA            2
GCA90_GCA          2
PassLive_GCA       2
PassDead_GCA       2
Drib_GCA           2
Sh_GCA             2
Fld_GCA            2
Def_GCA            2
dtype: int64

In [12]:
standard_data = pd.read_csv(DATA_DIR / 'player_standard.csv', low_memory=False)

drop_cols = ['Pos', 'Age', 'Url', 'xG_Expected', 'npxG_Expected', 'Ast']

mf_standard_data = standard_data[(standard_data['Season_End_Year'] == 2023) & (standard_data['Pos'].str.contains('MF', na=False))].drop(columns=drop_cols)
mf_standard_data

,Season_End_Year,Squad,Comp,Player,Nation,Born,MP_Playing,Starts_Playing,Min_Playing,Mins_Per_90_Playing,...,G+A_Per,G_minus_PK_Per,G+A_minus_PK_Per,xAG_Expected,npxG+xAG_Expected,xG_Per,xAG_Per,xG+xAG_Per,npxG_Per,npxG+xAG_Per
35669,2023,Ajaccio,Ligue 1,Mickaël Barreto,FRA,1991.0,4,1,144,1.6,...,0.00,0.00,0.00,0.2,0.3,0.07,0.10,0.17,0.07,0.17
35670,2023,Ajaccio,Ligue 1,Cyrille Bayala,BFA,1996.0,12,10,726,8.1,...,0.12,0.12,0.12,0.1,1.1,0.12,0.01,0.14,0.12,0.14
35671,2023,Ajaccio,Ligue 1,Youcef Belaïli,ALG,1992.0,3,2,177,2.0,...,0.00,0.00,0.00,0.4,0.4,0.02,0.20,0.22,0.02,0.22
35673,2023,Ajaccio,Ligue 1,Yanis Cimignani,FRA,2002.0,8,3,279,3.1,...,0.00,0.00,0.00,0.1,0.3,0.06,0.03,0.09,0.06,0.09
35674,2023,Ajaccio,Ligue 1,Mathieu Coutadeur,FRA,1986.0,10,7,631,7.0,...,0.00,0.00,0.00,0.5,0.6,0.00,0.08,0.08,0.00,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38001,2023,Wolves,Premier League,Rúben Neves,POR,1997.0,12,12,1080,12.0,...,0.25,0.17,0.17,0.3,0.9,0.12,0.02,0.14,0.05,0.07
38002,2023,Wolves,Premier League,Matheus Nunes,POR,1998.0,11,11,846,9.4,...,0.11,0.00,0.11,0.8,1.9,0.11,0.09,0.20,0.11,0.20
38003,2023,Wolves,Premier League,Daniel Podence,POR,1995.0,13,11,952,10.6,...,0.19,0.19,0.19,1.5,3.2,0.16,0.14,0.31,0.16,0.31
38006,2023,Wolves,Premier League,Adama Traoré,ESP,1996.0,10,5,509,5.7,...,0.18,0.18,0.18,0.7,1.2,0.09,0.12,0.21,0.09,0.21
38007,2023,Wolves,Premier League,Boubacar Traoré,MLI,2001.0,6,2,205,2.3,...,0.00,0.00,0.00,0.0,0.0,0.01,0.00,0.01,0.01,0.01

In [13]:
mf_standard_data.isna().sum()

Season_End_Year        0
Squad                  0
Comp                   0
Player                 0
Nation                 0
Born                   0
MP_Playing             0
Starts_Playing         0
Min_Playing            0
Mins_Per_90_Playing    0
Gls                    0
G_minus_PK             0
PK                     0
PKatt                  0
CrdY                   0
CrdR                   0
Gls_Per                0
Ast_Per                0
G+A_Per                0
G_minus_PK_Per         0
G+A_minus_PK_Per       0
xAG_Expected           2
npxG+xAG_Expected      2
xG_Per                 2
xAG_Per                2
xG+xAG_Per             2
npxG_Per               2
npxG+xAG_Per           2
dtype: int64

In [14]:
# Merge all dataframes on common identifier columns
merged_data = mf_possesion_data_no_redundant.merge(
    mf_passing_data_no_redundant, 
    on=['Player', 'Season_End_Year', 'Squad', 'Nation', 'Pos', 'Age', 'Born', 'Comp', 'Mins_Per_90'], 
    how='outer'
).merge(
    mf_shooting_data_no_redundant, 
    on=['Player', 'Season_End_Year', 'Squad', 'Nation', 'Pos', 'Age', 'Born', 'Comp', 'Mins_Per_90'], 
    how='outer'
).merge(
    mf_defense_data_no_redundant, 
    on=['Player', 'Season_End_Year', 'Squad', 'Nation', 'Pos', 'Age', 'Born', 'Comp', 'Mins_Per_90'], 
    how='outer'
).merge(
    mf_gca_data, 
    on=['Player', 'Season_End_Year', 'Squad', 'Nation', 'Pos', 'Age', 'Born', 'Comp', 'Mins_Per_90'], 
    how='outer'
).merge(
    mf_standard_data,
    on=['Player', 'Season_End_Year','Squad', 'Nation', 'Comp', 'Born'],
    how='inner'
    )

merged_data.drop_duplicates(inplace=True)

In [15]:
merged_data.columns.tolist()

['Season_End_Year',
 'Squad',
 'Comp',
 'Player',
 'Nation',
 'Pos',
 'Age',
 'Born',
 'Mins_Per_90',
 'Touches_Touches',
 'Def Pen_Touches',
 'Def 3rd_Touches',
 'Mid 3rd_Touches',
 'Att 3rd_Touches',
 'Att Pen_Touches',
 'Live_Touches',
 'Succ_Dribbles',
 'Att_Dribbles',
 'Rec_Receiving',
 'Prog_Receiving',
 'Mis_Dribbles',
 'Dis_Dribbles',
 'Cmp_Total',
 'Att_Total',
 'TotDist_Total',
 'PrgDist_Total',
 'Cmp_Short',
 'Att_Short',
 'Cmp_Medium',
 'Att_Medium',
 'Cmp_Long',
 'Att_Long',
 'Ast',
 'xA',
 'KP',
 'Final_Third',
 'PPA',
 'CrsPA',
 'Prog',
 'xAG',
 'A_minus_xAG',
 'Gls_Standard',
 'Sh_Standard',
 'SoT_Standard',
 'Sh_per_90_Standard',
 'SoT_per_90_Standard',
 'PK_Standard',
 'PKatt_Standard',
 'FK_Standard',
 'xG_Expected',
 'npxG_Expected',
 'G_minus_xG_Expected',
 'np:G_minus_xG_Expected',
 'Tkl_Tackles',
 'TklW_Tackles',
 'Def 3rd_Tackles',
 'Mid 3rd_Tackles',
 'Att 3rd_Tackles',
 'Tkl_Vs',
 'Att_Vs',
 'Past_Vs',
 'Blocks_Blocks',
 'Sh_Blocks',
 'Pass_Blocks',
 'Int',
 'Tkl+Int',
 'Clr',
 'Err',
 'SCA_SCA',
 'SCA90_SCA',
 'PassLive_SCA',
 'PassDead_SCA',
 'Drib_SCA',
 'Sh_SCA',
 'Fld_SCA',
 'Def_SCA',
 'GCA_GCA',
 'GCA90_GCA',
 'PassLive_GCA',
 'PassDead_GCA',
 'Drib_GCA',
 'Sh_GCA',
 'Fld_GCA',
 'Def_GCA',
 'MP_Playing',
 'Starts_Playing',
 'Min_Playing',
 'Mins_Per_90_Playing',
 'Gls',
 'G_minus_PK',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'Gls_Per',
 'Ast_Per',
 'G+A_Per',
 'G_minus_PK_Per',
 'G+A_minus_PK_Per',
 'xAG_Expected',
 'npxG+xAG_Expected',
 'xG_Per',
 'xAG_Per',
 'xG+xAG_Per',
 'npxG_Per',
 'npxG+xAG_Per']

In [16]:
merged_data = merged_data.dropna()
merged_data

,Season_End_Year,Squad,Comp,Player,Nation,Pos,Age,Born,Mins_Per_90,Touches_Touches,...,G+A_Per,G_minus_PK_Per,G+A_minus_PK_Per,xAG_Expected,npxG+xAG_Expected,xG_Per,xAG_Per,xG+xAG_Per,npxG_Per,npxG+xAG_Per
0,2023,Nice,Ligue 1,Aaron Ramsey,WAL,MF,31-303,1990.0,4.1,289.0,...,0.23,0.23,0.23,0.2,1.1,0.22,0.03,0.25,0.22,0.25
1,2023,Sampdoria,Serie A,Abdelhamid Sabiri,MAR,MF,25-331,1996.0,9.3,495.0,...,0.11,0.11,0.11,1.3,2.3,0.11,0.13,0.25,0.11,0.25
2,2023,Osasuna,La Liga,Abdessamad Ezzalzouli,MAR,"MF,FW",20-312,2001.0,3.5,184.0,...,0.58,0.00,0.58,0.7,1.4,0.18,0.21,0.39,0.18,0.39
3,2023,Sassuolo,Serie A,Abdou Harroui,NED,MF,24-285,1998.0,2.1,101.0,...,0.46,0.46,0.46,0.0,0.3,0.15,0.01,0.16,0.15,0.16
4,2023,Nantes,Ligue 1,Abdoul Kader Bamba,FRA,MF,28-153,1994.0,0.8,51.0,...,0.00,0.00,0.00,0.0,0.1,0.11,0.04,0.15,0.11,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1019,2023,Rayo Vallecano,La Liga,Óscar Trejo,ARG,"MF,FW",34-182,1988.0,8.3,440.0,...,0.36,0.12,0.36,0.9,1.6,0.18,0.11,0.29,0.08,0.19
1020,2023,Rayo Vallecano,La Liga,Óscar Valentín,ESP,MF,28-066,1994.0,7.6,463.0,...,0.00,0.00,0.00,0.4,0.6,0.02,0.05,0.07,0.02,0.07
1021,2023,Lecce,Serie A,Þórir Jóhann Helgason,ISL,MF,22-027,2000.0,1.7,59.0,...,0.00,0.00,0.00,0.3,0.4,0.03,0.21,0.23,0.03,0.23
1022,2023,Manchester City,Premier League,İlkay Gündoğan,GER,MF,32-001,1990.0,6.9,510.0,...,0.38,0.25,0.38,2.0,3.6,0.20,0.25,0.45,0.20,0.45
1023,2023,Lens,Ligue 1,Łukasz Poręba,POL,MF,22-226,2000.0,2.2,113.0,...,0.45,0.00,0.45,0.6,1.1,0.26,0.25,0.51,0.26,0.51

In [17]:
merged_data.isna().sum().sum()

np.int64(0)

In [18]:
merged_data.to_csv(PROJECT_DIR / 'mf_data_europe_2023.csv', index=False)